ServerBundle\Entity\GameServer:
    type: entity
    table: null
    repositoryClass: ServerBundle\Repository\GameServerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        templateId:
            type: integer
        serverName:
            type: string
            length: 255
        gameName:
            type: string
            length: 255
        ownerId:
            type: integer
        startupCommand:
            type: text
        updateCommand:
            type: text
        playerSlots:
            type: string
            length: 255
        ram:
            type: string
            length: 255
        queryEngine:
            type: string
            length: 255
    lifecycleCallbacks: {  }
